### PR TITLE
S3 upload

### PR DESCRIPTION
**Pull request by jackcarlisle**
Finished the s3 gulp example. All ready to merge!

### CODE REVIEW

**Comment by nelsonic** [comment]
@jackcarlisle I cannot access the codeship build log ... can you add me?

**Comment by jackcarlisle** [comment]
@nelsonic Sure! Just sent you the invitation

**Comment by nelsonic** [comment]
@jackcarlisle received the invite:
codeship-invite
But when I click on it I see a `404`:
codeship-404
:cry:

**Comment by nelsonic** [comment]
@jackcarlisle can you please try re-sending the invitation?
or past the relevant lines of the build log so we know why the build is failing?

**Comment by jackcarlisle** [comment]
@nelsonic I've resent it. Let me know if it doesn't work and I'll paste the log here

**Comment by nelsonic** [comment]
@jackcarlisle give that the CI checks fail because of ES6 and will otherwise pass, I'm merging this branch to get the S3 work integrated. :+1:

**Pull request merged**
