### PR TITLE
More testing examples

### PR DESCRIPTION
**Pull request by nikhilaravi**
Added tests for 
- simple Lambda function
- Dynamo DB triggered lambda function

Also added 
- example test using 'ava' instead of code and lab. 
- mockContext module using callbacks instead of promises. 
### TODO

Need to adds some more notes to readme

### CODE REVIEW

**Comment by nelsonic** [comment]
How was the NodeGirls Hackathon/Day ? :wink:

**Comment by nikhilaravi** [comment]
@nelsonic hackday was good! But it reminded me why I hate css...!

**Comment by nelsonic** [comment]
Surely you don't "_hate_" CSS...? :open_mouth: 
You just haven't had a chance to practice with it enough... :wink: 
FAC _barely_ touches CSS. :disappointed:

**Comment by nikhilaravi** [comment]
@nelsonic yes thats true. I will practice!

**Comment by nikhilaravi** [comment]
@nelsonic this is ready to merge - What do you think about the options for testing?:
1. using mock-context npm module (and possibly ava)
2. mocking context ourselves using callbacks

I will write notes for the readme based on which option you think is most useful!

**Comment by nelsonic** [comment]
@nikhilaravi I'm _excited_ about [_ava_](https://github.com/sindresorhus/ava) ... 
I _prefer_ to use callbacks wherever possible because there's no _magic_ or dependencies. 

Your examples are _really_ good. :+1:

**Comment by nikhilaravi** [comment]
@nelsonic thanks!  :blush: @benjaminlees what do you think?

**Pull request merged**
