### PR TITLE
updating readme for aws node version

### PR DESCRIPTION
**Pull request by Jbarget**

### CODE REVIEW

**Comment by Jbarget** [comment]
im out of practice with referencing issues in commits, sozza (i tried to make up for it) :)

**Comment by nelsonic** [comment]
@Jbarget lol. out of practice... what do you guys use to keep track of your work? JIRA? 😜 
Thanks for making the update! 🎉

**Comment by Jbarget** [comment]
Ugh it feels good to have someone else merge in a PR of mine! im working solo so been merging my own stuff in.
JIRAish. but mostly slack 😆

**Comment by nelsonic** [comment]
minions-whaaaaat
Tracking work via Slack...?! You're Such a Maverick! 
solo... 😞  where's your [_Wingman_](https://youtu.be/sz_EnEx9m5g?t=23s)...?

**Comment by Jbarget** [comment]
ha its not me I promise :) 
no wingman yet but only a sprint left. so been looking forward to the old pair programming again  :)

**Pull request merged**
